### ISSUE TITLE
已经在10.14上成功驱动显卡了

### ISSUE THREAD

**Issue by WallfacerMajor** [TioaTyan/Lenovo_Legion_Y7000-1060_Hackintosh#2]
如果你是在10.13.6的特别版后的版本，可以试试使用whatevergreen驱动
参照
https://blog.daliansky.net/Coffee-Lake-frame-buffer-patch-and-UHD630-Coffee-Lake-ig-platform-id-data-finishing.html
以及原文
https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/#post-1780416

**Comment by WallfacerMajor** [comment]
但是目前还存在很多问题
多次开机尝试中有时候是显示屏内建，有时候显示为外屏，开机黑屏一段时间才能亮屏等问题

**Comment by TioaTyan** [comment]
thx
